// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLM9apmIIUl2DEi9hzRHFfntuZQqD_fF0',
    appId: '1:477070524005:web:7468946fe294abac9a908c',
    messagingSenderId: '477070524005',
    projectId: 'fitlab-6a86c',
    authDomain: 'fitlab-6a86c.firebaseapp.com',
    storageBucket: 'fitlab-6a86c.firebasestorage.app',
    measurementId: 'G-710FD3BDWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqKEA61KAURE9nNnRB_ishXhAUR0QaViI',
    appId: '1:477070524005:android:5d88a9465abc5b2d9a908c',
    messagingSenderId: '477070524005',
    projectId: 'fitlab-6a86c',
    storageBucket: 'fitlab-6a86c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHWFF7c7HS7JUoNigDez0K-_MxE1cuQjo',
    appId: '1:477070524005:ios:ccafae95279a16cd9a908c',
    messagingSenderId: '477070524005',
    projectId: 'fitlab-6a86c',
    storageBucket: 'fitlab-6a86c.firebasestorage.app',
    iosBundleId: 'com.example.clickCounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu89R9mtnHcq0To5hQS8f5PfLrthZq6U0',
    appId: '1:688582750365:ios:f7197d977d27ecd63d2474',
    messagingSenderId: '688582750365',
    projectId: 'projeto-exemplo-3916b',
    storageBucket: 'projeto-exemplo-3916b.firebasestorage.app',
    iosBundleId: 'com.carol.fitlab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxYU5F8NMrbnXXGUmaPjcWCyJUkSbwP5Q',
    appId: '1:688582750365:web:c1deaa7cdcd896223d2474',
    messagingSenderId: '688582750365',
    projectId: 'projeto-exemplo-3916b',
    authDomain: 'projeto-exemplo-3916b.firebaseapp.com',
    storageBucket: 'projeto-exemplo-3916b.firebasestorage.app',
    measurementId: 'G-J21BMT5EN7',
  );

}